name: Auto-approve -> merge owner PRs

on:
  issue_comment:
    types: [created]
  workflow_dispatch:


jobs:
  approve_automerge:
    runs-on: ubuntu-latest
    if: >
      github.event.issue.pull_request &&
      github.event.comment.body == 'Approved' &&
      github.event.comment.user.login == github.repository_owner
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Approve PR
        run: gh pr review ${{ github.event.issue.number }} --approve
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Enable auto-merge (merge commit)
        run: gh pr merge ${{ github.event.issue.number }} --auto --merge
        env:
          GITHUB_TOKEN: ${{ github.token }}