name: get-application-repo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout selfhost repo
        uses: actions/checkout@v4

      - name: Checkout portfolio main branch
        uses: actions/checkout@v4
        with:
          repository: iryandydanish/danish_portfolio
          ref: main
          path: application/portfoliowebsite/src
          token: ${{ secrets.GH_PAT }}